FlaskAssesment/app/__init__.py
from flask import Flask
from app.routes import main_routes
from app.product_routes import product_routes


def create_app():
    app = Flask(__name__)
    app.register_blueprint(main_routes)
    app.register_blueprint(product_routes)
    return app

FlaskAssesment/app/routes.py
from flask import Blueprint, render_template

main_routes = Blueprint('main_routes', __name__)

# This is the route that will be displayed when the user visits the root URL of the site.


@main_routes.route('/')
def home():
    return render_template('home.html', title='Home', message='This is the home page.')


@main_routes.route('/about')
def about():
    return render_template('about.html', title='About', message='This is the about page.')

FlaskAssesment/app/templates/about.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1>{{title}}</h1>
<p>{{message}}</p>
<p>Welcome to the about page</p>
{% endblock %}

FlaskAssesment/app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>

<body>

    <header class="container">
        <h1 class="text-center my-4">My Flask Project</h1>
        <nav class="nav justify-content-center mb-4">
            <a class="nav-link" href="{{ url_for('main_routes.home')}}">Home</a>
            <a class="nav-link" href="{{ url_for('main_routes.about') }}">About</a>
            <a class="nav-link" href="{{ url_for('product_routes.index') }}">Products</a>
            <!-- <ul>
                <li><a href="{{ url_for('main_routes.home')}}">Home</a></li>
                <li><a href="{{ url_for('main_routes.about') }}">About</a></li>
                <li><a href="{{ url_for('product_routes.index') }}">Products</a></li>
            </ul> -->
        </nav>
    </header>

    <main class="container">
        {% block content %}
        {% endblock %}
    </main>

    <footer class="container">
        <p>&copy; 2020 My Flask Project</p>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>

</body>

</html>

FlaskAssesment/app/templates/home.html
{% extends "base.html" %}

{% block title %}{{title}}{% endblock %}

{% block content %}
<h1>{{title}}</h1>
<p>{{message}}</p>
<p>Welcome to the home page</p>
{% endblock %}

FlaskAssesment/app/templates/products/create.html
{% extends "base.html" %}

{% block title %}Create Product{% endblock %}

{% block content %}

<h2 class="text-center">Creating a New Product</h2>
<form method="post" action="{{ url_for('product_routes.create') }}" class="container">
    <div class="mb-3">
        <label for="id" class="form-label">ID:</label>
        <input type="number" id="id" name="id" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" id="name" name="name" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Price:</label>
        <input type="number" id="price" name="price" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Create Product</button>
</form>


<!-- <h2>Creating a New Product</h2>
<form method="post" action="{{ url_for('product_routes.create') }}">
    <label for="id">ID:</label>
    <input type="number" id="id" name="id" required>
    <br>
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" required>
    <br>
    <label for="price">Price:</label>
    <input type="number" id="price" name="price" required>
    <br>
    <button type="submit">Create Product</button>
</form> -->

{% endblock %}

FlaskAssesment/app/templates/products/index.html
{% extends "base.html" %}

{% block title %}Products Page{% endblock %}

{% block content %}

<a class="btn btn-success" href="{{ url_for('product_routes.create') }}">Create Product</a>

<h3 class="text-center">Product List</h3>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Id</th>
            <th>name</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.id }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.price }}</td>
            <td>
                <a href="{{ url_for('product_routes.update', product_id=product.id) }}"
                    class="btn btn-primary">Update</a>
                <a href="{{ url_for('product_routes.delete', product_id=product.id) }}"
                    class="btn btn-danger">Delete</a>
            </td>
        </tr>
        {% endfor %}
</table>



<!-- <ul>
    {% for product in products %}
    <li>
        {{product.id}} - {{ product.name }} - ${{ product.price }}
        <a href="{{ url_for('product_routes.update', product_id=product.id) }}">Update</a>
        <a href="{{ url_for('product_routes.delete', product_id=product.id) }}">Delete</a>
    </li>
    {% endfor %}
</ul> -->

{% endblock %}

FlaskAssesment/app/templates/products/update.html
{% extends "base.html" %}

{% block title %}Create Product{% endblock %}

{% block content %}

<h2 class="text-center">Updating an Existing Product</h2>
<form method="post" action="{{ url_for('product_routes.update', product_id=product_id)}}" class="container">
    <div class="mb-3">
        <label for="id" class="form-label">ID:</label>
        <input type="number" id="id" name="id" value="{{ product.id }}" class="form-control" readonly>
    </div>
    <div class="mb-3">
        <label for="name" class="form-label">Name:</label>
        <input type="text" id="name" name="name" value="{{ product.name }}" class="form-control" required>
    </div>
    <div class="mb-3">
        <label for="price" class="form-label">Price:</label>
        <input type="number" id="price" name="price" value="{{ product.price }}" class="form-control" required>
    </div>
    <button type="submit" class="btn btn-primary">Update Product</button>
</form>

<!-- <h2>Updating an Existing Product</h2>
<form method="post" action="{{ url_for('product_routes.update', product_id=product_id)}}">
    <label for="id">ID:</label>
    <input type="number" id="id" name="id" value="{{ product.id }}" readonly>
    <br>
    <label for="name">Name:</label>
    <input type="text" id="name" name="name" value="{{ product.name }}" required>
    <br>
    <label for="price">Price:</label>
    <input type="number" id="price" name="price" value="{{ product.price }}" required>
    <br>
    <button type="submit">Update Product</button>
</form> -->

{% endblock %}